package com.kal1van1ch.banktgbot.model;

public enum Status {
    DEFAULT,
    WAITING_FOR_AMOUNT,
    WAITING_FOR_NUMBER,
    WAITING_FOR_BANK,
    TRANSFER_LINK,
    WAITING_FIRST_NAME,
    WAITING_LAST_NAME,
    WAITING_PATRONYMIC,
    WAITING_PHONE_NUMBER,
    TRANSFER_SUCCESSFUL_REGISTRATION,
    HELP
}
