package com.kal1van1ch.banktgbot.model;

public enum Status {
    DEFAULT,
    WAITING,
    WAITING_FOR_AMOUNT,
    WAITING_FOR_NUMBER,
    WAITING_FOR_BANK,
    TRANSFER_LINK,
    MAKE_TRANSACTION,
    WAITING_FIRST_NAME,
    WAITING_LAST_NAME,
    WAITING_PATRONYMIC,
    WAITING_PHONE_NUMBER,
    TRANSFER_SUCCESSFUL_REGISTRATION,
    HELP,
    EDIT,
    EDIT_DATA,
    EDIT_FIRST_NAME,
    EDIT_LAST_NAME,
    EDIT_PATRONYMIC,
    EDIT_PHONE_NUMBER,
    DELETE,
    DELETE_ACTION
}
